<?php

namespace PROCERGS\LoginCidadao\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActionLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionLogRepository extends EntityRepository
{

}
