services:
    LoginCidadao\SupportBundle\Service\SupportHandler:
        class: LoginCidadao\SupportBundle\Service\SupportHandler
        arguments:
            - "@security.authorization_checker"
            - "@lc.person.repository"
            - "@lc.sent_email.repository"

    LoginCidadao\SupportBundle\Twig\SupportExtensions:
        clas: LoginCidadao\SupportBundle\Twig\SupportExtensions
        tags:
            - { name: 'twig.extension' }
