services:
    LoginCidadao\SupportBundle\Service\SupportHandler:
        class: LoginCidadao\SupportBundle\Service\SupportHandler
        arguments:
            - "@security.authorization_checker"
            - "@lc.person.repository"
            - "@lc.sent_email.repository"
