<?php
/**
 * This file is part of the login-cidadao project or it's bundles.
 *
 * (c) Guilherme Donato <guilhermednt on github>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LoginCidadao\PhoneVerificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneVerificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @codeCoverageIgnore
 */
class PhoneVerificationRepository extends EntityRepository
{
    public function countBadges()
    {
        return $this->createQueryBuilder('ph')
            ->select('COUNT(p)')
            ->innerJoin('LoginCidadaoCoreBundle:Person', 'p', 'WITH', 'ph.person = p')
            ->andWhere('ph.verifiedAt IS NOT NULL')
            ->getQuery()->getSingleScalarResult();
    }
}
