php_version: 7.1

pre_composer_script: |
    #!/bin/bash

    sed -i -e "s/database_driver:.*/database_driver: pdo_mysql/" app/config/parameters.yml.dist
    sed -i -e "s/database_server_version:.*/database_server_version: 5.6/" app/config/parameters.yml.dist
    apt-get install -y redis-server
    service redis-server start

php_ini: |
    extension=pdo_mysql.so

exclude_patterns:
    - batch/*
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app_*.php
    - app/Resources/node_modules/*

rules:
    # Although we are escaping stuff, SensioLabs is not detecting ir properly.
    twig.xss_vulnerability:
        enabled: false
    task_todo_comment:
        enabled: false
