web:
    build: .
    links:
        - db
    environment:
        SYMFONY__DATABASE__DRIVER: pdo_mysql
        SYMFONY__DATABASE__HOST: db
        SYMFONY__DATABASE__PORT: 3306
        SYMFONY__DATABASE__NAME: login_cidadao
        SYMFONY__DATABASE__USER: logincidadao
        SYMFONY__DATABASE__PASSWORD: logincidadao
    ports:
        - "80:80"
    volumes:
        - ".:/var/www/symfony"
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: login_cidadao
        MYSQL_USER: logincidadao
        MYSQL_PASSWORD: logincidadao
