imports:
    - { resource: config.yml }

parameters:
    base_path: /app_dev.php

framework:
    translator:
        logging: %log_translator%
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: %web_profiler_toolbar%
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

assetic:
    use_controller: true

swiftmailer:
    delivery_address: '%dev_email_destination%'
