services:
    phone_verification.options:
        class: LoginCidadao\PhoneVerificationBundle\Service\PhoneVerificationOptions
        arguments:
            - "%lc.phone_verification.options.code.length%"
            - "%lc.phone_verification.options.code.use_numbers%"
            - "%lc.phone_verification.options.code.case_sensitive%"
            - "%lc.phone_verification.options.code.use_lower%"
            - "%lc.phone_verification.options.code.use_upper%"
            - "%lc.phone_verification.options.sms.resend_timeout%"
            - "%lc.phone_verification.options.token.length%"
            - "%lc.phone_verification.options.require_validation_threshold%"
        lazy: true

    phone_verification.blocklist.options:
        class: LoginCidadao\PhoneVerificationBundle\Service\BlocklistOptions
        arguments:
            - "%lc.phone_verification.options.blocklist.auto_block_limit%"
        lazy: true

    phone_verification:
        class: LoginCidadao\PhoneVerificationBundle\Service\PhoneVerificationService
        arguments:
            - "@phone_verification.options"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
        lazy: true

    phone_verification.events.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\PhoneVerificationSubscriber
        arguments:
            - "@phone_verification"
        calls:
            - ['setLogger', ["@?logger"]]
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: phone_verification }

    phone_verification.profile_edit.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\ProfileEditSubscriber
        tags:
            - { name: kernel.event_subscriber }

    phone_verification.user_registration.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\UserRegistrationSubscriber
        arguments:
            - "@phone_verification"
            - "@task_stack.manager"
        tags:
            - { name: kernel.event_subscriber }

    phone_verification.person.serialize.listener:
        class: LoginCidadao\PhoneVerificationBundle\Event\PersonSerializeEventListener
        arguments:
            - "@phone_verification"
        tags:
            - { name: jms_serializer.event_listener, event: serializer.pre_serialize, method: onPreSerialize }

    phone_verification.tasks.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\TaskSubscriber
        arguments:
            - "@security.token_storage"
            - "@phone_verification"
            - "%lc.phone_verification.options.enabled%"
        tags:
            - { name: kernel.event_subscriber }

    phone_verification.badges.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\BadgesSubscriber
        arguments:
            - "@phone_verification"
            - "@translator"
            - "@doctrine.orm.entity_manager"
            - "%lc.phone_verification.options.enabled%"
        tags:
            - { name: kernel.event_subscriber }

    phone_verification.blocklist.subscriber:
        class: LoginCidadao\PhoneVerificationBundle\Event\BlocklistSubscriber
        arguments:
            - "@phone_verification.blocklist"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    phone_verification.form:
        class: LoginCidadao\PhoneVerificationBundle\Form\PhoneVerificationType
        arguments:
            - "@phone_verification.options"
        tags:
            - { name: form.type }

    phone_verification.sent_verification.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\PhoneVerificationBundle\Entity\SentVerification

    phone_verification.sms_status:
        class: LoginCidadao\PhoneVerificationBundle\Service\SmsStatusService
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@phone_verification.sent_verification.repository"

    phone_verification.blocklist:
        class: LoginCidadao\PhoneVerificationBundle\Service\Blocklist
        arguments:
            - "@lc.user_manager"
            - "@lc.mailer"
            - "@doctrine.orm.entity_manager"
            - "@phone_verification"
            - "@phone_verification.blocklist.options"
