<?php

namespace LoginCidadao\TOSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgreementRepository extends EntityRepository
{
}
