procergso_auth_homepage:
    path:  /hello/{name}
    defaults: { _controller: PROCERGSOAuthBundle:Default:index }

procergs_oauth_init:
    path: /initClient
    defaults: { _controller: PROCERGSOAuthBundle:Client:initClient }

procergs_oauth_getid:
    path: /getPub/{id}
    defaults: { _controller: PROCERGSOAuthBundle:Client:getPublicId }
