parameters:
    lc_accesstoken_manager.class: PROCERGS\OAuthBundle\Model\AccessTokenManager

services:
    oauth_event_listener:
        class: PROCERGS\OAuthBundle\EventListener\OAuthEventListener
        arguments: ['@doctrine', '@service_container']
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess}
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

    procergs_logincidadao.oauth.client_manager:
        class: PROCERGS\OAuthBundle\Entity\ClientManager
        parent: fos_oauth_server.client_manager.default

    lc_accesstoken_manager:
        class: %lc_accesstoken_manager.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @security.token_storage
