<?php
/**
 * This file is part of the login-cidadao project or it's bundles.
 *
 * (c) Guilherme Donato <guilhermednt on github>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LoginCidadao\AccountRecoveryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use LoginCidadao\CoreBundle\Model\PersonInterface;

/**
 * AccountRecoveryDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRecoveryDataRepository extends EntityRepository
{
    public function findByPerson(PersonInterface $person): ?AccountRecoveryData
    {
        /** @var AccountRecoveryData|null $data */
        $data = $this->findOneBy(['person' => $person]);

        return $data;
    }
}
