parameters:
    lc_accesstoken_manager.class: LoginCidadao\OAuthBundle\Model\AccessTokenManager
    lc.organization.form.class: LoginCidadao\OAuthBundle\Form\OrganizationType

services:
    oauth_scope_finder:
        class: LoginCidadao\OAuthBundle\Helper\ScopeFinderHelper
        arguments:
            - "@request_stack"
            - "@fos_oauth_server.authorize.form"

    oauth_event_listener:
        class: LoginCidadao\OAuthBundle\EventListener\OAuthEventListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@oauth_scope_finder"
            - "@oidc.subject_identifier.service"
        tags:
            - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess}
            - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

    lc.oauth.client_manager:
        class: LoginCidadao\OAuthBundle\Entity\ClientManager
        parent: fos_oauth_server.client_manager.default

    lc_accesstoken_manager:
        class: %lc_accesstoken_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"

    lc.organization.form:
        class: %lc.organization.form.class%
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
        tags:
            - { name: form.type, alias: lc_organization }

    lc.client.repository:
        myrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\OAuthBundle\Entity\Client

    lc.access_token.repository:
        myrepository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\OAuthBundle\Entity\AccessToken
