<?php

namespace PROCERGS\LoginCidadao\AccountingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcergsLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcergsLinkRepository extends EntityRepository
{
}
