services:
    lc.remote_claims.http_client:
        class: GuzzleHttp\Client
        arguments:
            - verify: true # set to false for testing purposes only

    lc.remote_claims.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\RemoteClaimsBundle\Entity\RemoteClaim

    lc.remote_claims.authorization.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - LoginCidadao\RemoteClaimsBundle\Entity\RemoteClaimAuthorization

    lc.remote_claims.fetcher:
        class: LoginCidadao\RemoteClaimsBundle\Fetcher\RemoteClaimFetcher
        arguments:
            - "@lc.remote_claims.http_client"
            - "@doctrine.orm.entity_manager"
            - "@lc.remote_claims.repository"
            - "@lc.client_manager"
            - "@event_dispatcher"

    lc.remote_claims.manager:
        class: LoginCidadao\RemoteClaimsBundle\Model\RemoteClaimManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@lc.remote_claims.authorization.repository"
            - "@lc.remote_claims.repository"
            - "@lc.authorization.manager"

    lc.remote_claims.auth_event_subscriber:
        class: LoginCidadao\RemoteClaimsBundle\EventSubscriber\AuthorizationSubscriber
        arguments:
            - "@lc.remote_claims.manager"
            - "@lc.remote_claims.fetcher"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }

    lc.remote_claims.person.serialize.subscriber:
        class: LoginCidadao\RemoteClaimsBundle\EventSubscriber\PersonSerializeEventSubscriber
        arguments:
            - "@lc_accesstoken_manager"
            - "@lc.remote_claims.manager"
            - "@lc.remote_claims.fetcher"
            - "@lc.api.version"
        tags:
            - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize }

    lc.remote_claims.subscriber:
        class: LoginCidadao\RemoteClaimsBundle\EventSubscriber\RemoteClaimSubscriber
        arguments:
            - "@lc.remote_claims.manager"
        tags:
            - { name: kernel.event_subscriber }
