<?php

namespace LoginCidadao\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BackupCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackupCodeRepository extends EntityRepository
{
}
