<?php
/**
 * This file is part of the login-cidadao project or it's bundles.
 *
 * (c) Guilherme Donato <guilhermednt on github>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace LoginCidadao\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SentEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentEmailRepository extends EntityRepository
{
    public function findAllSentInTheLast24h($type, $indexedByReceiver = false)
    {
        $date = new \DateTime("-24 hours");
        $result = $this->getEntityManager()
            ->createQuery('SELECT s FROM LoginCidadaoCoreBundle:SentEmail s WHERE s.type = :type AND s.date >= :date')
            ->setParameter('type', $type)
            ->setParameter('date', $date)
            ->getResult();
        if ($indexedByReceiver) {
            $indexed = array();
            foreach ($result as $email) {
                $indexed[$email->getReceiver()] = $email;
            }
            return $indexed;
        } else {
            return $result;
        }
    }
}
